use_frameworks!

target 'XMTesseract_Example' do
  pod 'XMTesseract', :path => '../'

  target 'XMTesseract_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
